##################################################################################################
# Details Deployment
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  labels:
  {{- include "DETAILS.lables" . |nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
    {{- include "DETAILS.lables" . |nindent 8 }}
  template:
    metadata:
      labels:
      {{- include "DETAILS.lables" . |nindent 12 }}
    spec:
      serviceAccountName: bookinfo-details
      containers:
      - name: details
        image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000