# Default values for Details.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  replicaCount: 1
  name: productpage
  env: dev

  image:
    repository: docker.io/istio/examples-bookinfo-productpage-v1
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 1.17.0

  service:
    name: productpage
    type: ClusterIP
    port: 9080
  
  ServiceAccount:
    account: productpage


hpa:
  enabled: false


