# Default values for Details.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  replicaCount: 1
  name: productpage
  env: dev

  image:
    repository: 120583202101.dkr.ecr.us-east-1.amazonaws.com/genpact-apaas
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ui_v3.2.5.27

  service:
    name: productpage
    service: productpage
    type: ClusterIP
    port: 9080
  
  ServiceAccount:
    account: productpage


hpa:
  enabled: false


