---
##################################################################################################
#RoleBinding
##################################################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- include "EKS_Autoscaler.name" . |nindent 4 }}
  labels:
  {{- include "EKS_Autoscaler.lables01" . |nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.app.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.app.name }}
    namespace: kube-system
