---
##################################################################################################
#Role
##################################################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
{{- include "EKS_Autoscaler.name" . |nindent 4 }}
  labels:
  {{- include "EKS_Autoscaler.lables01" . |nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create","list","watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["cluster-autoscaler-status", "cluster-autoscaler-priority-expander"]
    verbs: ["delete", "get", "update", "watch"]
