---
##################################################################################################
#ServiceAccount
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  {{- include "EKS_Autoscaler.lables01" . |nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.app.ServiceAccount.role_arn }}
  {{- include "EKS_Autoscaler.name" . |nindent 2 }}
