---
##################################################################################################
# Ratings Deployment
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
  {{- include "Ratings.lables" . |nindent 4 }}
    version: {{ .Values.app.version }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
    {{- include "Ratings.lables" . |nindent 6 }}
      version: {{ .Values.app.version }}
  template:
    metadata:
      labels:
      {{- include "Ratings.lables" . |nindent 8 }}
        version: {{ .Values.app.version }}
    spec:
      serviceAccountName: bookinfo-ratings
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000