---
##################################################################################################
# Ratings ServiceAccount
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings
  labels:
    account: {{ .Values.app.ServiceAccount.account }}