---
##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
  {{- include "Productpage.lables" . |nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
  - port: {{ .Values.app.service.port }}
    name: http
  selector:
    app: {{ .Values.app.name }}

