---
##################################################################################################
# Productpage ServiceAccount
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-productpage
  labels:
    account: {{ .Values.app.name }}
