---
##################################################################################################
# Reviews Deployment
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.reviews-v1.name }}
  labels:
  {{- include "Reviews.lables" . |nindent 4 }}
  version: {{ .Values.app.reviews-v1.version }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
    {{- include "Reviews.lables" . |nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "Reviews.lables" . |nindent 8 }}
      version: {{ .Values.app.reviews-v1.version }}
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: {{ .Values.app.reviews-v1.name }}
        image: {{ .Values.app.image.reviews-v1.repository }}:{{ .Values.app.image.reviews-v1.tag }}
        imagePullPolicy: {{ .Values.app.image.reviews-v1.pullPolicy }}
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.reviews-v2.name }}
  labels:
  {{- include "Reviews.lables" . |nindent 4 }}
    version: {{ .Values.app.reviews-v2.version }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
    {{- include "Reviews.lables" . |nindent 6 }}
      version: {{ .Values.app.reviews-v2.version }}
  template:
    metadata:
      labels:
      {{- include "Reviews.lables" . |nindent 8 }}
        version: {{ .Values.app.reviews-v2.version }}
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: {{ .Values.app.reviews-v2.name }}
        image: {{ .Values.app.image.reviews-v2.repository }}:{{ .Values.app.image.reviews-v2.tag }}
        imagePullPolicy: {{ .Values.app.image.reviews-v2.pullPolicy }}
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.reviews-v3.name }}
  labels:
  {{- include "Reviews.lables" . |nindent 4 }}
    version: {{ .Values.app.reviews-v3.version }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
    {{- include "Reviews.lables" . |nindent 6 }}
      version: {{ .Values.app.reviews-v3.version }}
  template:
    metadata:
      labels:
      {{- include "Reviews.lables" . |nindent 8 }}
        version: {{ .Values.app.reviews-v3.version }}
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: {{ .Values.app.reviews-v3.name }}
        image: d{{ .Values.app.image.reviews-v3.repository }}:{{ .Values.app.image.reviews-v3.tag }}
        imagePullPolicy: {{ .Values.app.image.reviews-v3.pullPolicy }}
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}