---
##################################################################################################
# Reviews ServiceAccount
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
  labels:
    account: {{ .Values.app.ServiceAccount.name }}