# Default values for Details.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  replicaCount: 1
  name: reviews
  env: dev


  image:
    repository: docker.io/istio/examples-bookinfo-reviews-v1
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 1.17.0

  service:
    name: reviews
    type: ClusterIP
    port: 9080

  ServiceAccount:
    account: reviews

hpa:
  enabled: false


